import {test} from 'node:test';import assert from 'node:assert/strict';import {PermissionFlagsBits as P} from 'discord.js';
import {ROLE_ENV} from '../src/config-rules.js';import {wantedRoles,synchronizeRoles,assertManagedRoles} from '../src/role-policy.js';
function fixture(division=1){const d={id:division,memberRole:'member',adminRole:'team',rankRoles:Object.fromEntries(Object.keys(ROLE_ENV).map(k=>[k,k]))},roles=new Map(['member','team',...Object.keys(ROLE_ENV)].map(id=>[id,{id,permissions:{has:()=>false}}])),me={roles:{highest:{comparePositionTo:()=>1}}};const events=[],cache=new Set(['unrelated']);const user={roles:{cache,add:async id=>{events.push(['add',id]);cache.add(id);},remove:async id=>{events.push(['remove',id]);cache.delete(id);}}};const g={id:'guild',roles:{fetch:async()=>roles},members:{fetchMe:async()=>me}};return {d,g,roles,me,events,user,cache};}
test('unverified users receive nothing; each configured rank gets its own role after verification',async()=>{
 const f=fixture();for(const [name,key]of [['Líder','leader'],['Sub-líder','subleader'],['High member','high'],['Moderador','moderator'],['Recrutador','recruiter'],['Veterano','veteran'],['Novato','rookie'],['Aliado','ally']]){
 const m={account_kind:'membro',division:1,member_rank:name,verified:false};assert.equal(wantedRoles(m,f.d).size,0);m.verified=true;const wanted=wantedRoles(m,f.d);assert.ok(wanted.has(key));assert.ok(wanted.has('member'));assert.equal(wanted.has('team'),['leader','subleader','moderator'].includes(key));
 }
 assert.deepEqual([...wantedRoles({verified:true,division:1,account_kind:'membro',member_rank:'Patente personalizada'},f.d)],['member']);
});
test('division and alliance rules apply to access, rank and team roles together',()=>{const {d}=fixture(2);for(const rank of ['Líder','Sub líder','High member'])assert.ok(wantedRoles({account_kind:'membro',division:1,member_rank:rank,verified:true},d).has('member'));assert.equal(wantedRoles({account_kind:'membro',division:1,member_rank:'Moderador',verified:true},d).size,0);const ally=wantedRoles({account_kind:'aliado',member_rank:'Líder',division:1,verified:true},d);assert.ok(ally.has('ally'));assert.equal(ally.has('team'),false);});
test('promotion grants team; demotion and revocation remove stale roles and preserve unrelated roles',async()=>{const f=fixture();const m={account_kind:'membro',division:1,verified:true,member_rank:'Sub líder'};await synchronizeRoles(f.g,f.d,f.user,m);assert.deepEqual([...f.cache].sort(),['member','subleader','team','unrelated'].sort());m.member_rank='Moderador';await synchronizeRoles(f.g,f.d,f.user,m);assert.ok(!f.cache.has('subleader'));assert.ok(f.cache.has('moderator'));m.member_rank='Recrutador';await synchronizeRoles(f.g,f.d,f.user,m);assert.ok(!f.cache.has('team'));assert.ok(!f.cache.has('moderator'));assert.ok(f.cache.has('recruiter'));m.verified=false;await synchronizeRoles(f.g,f.d,f.user,m);assert.deepEqual([...f.cache],['unrelated']);});
test('deleted IFJ revokes all managed roles; runtime checks reject elevated or unmanageable roles',async()=>{const f=fixture();for(const id of f.roles.keys())f.cache.add(id);await synchronizeRoles(f.g,f.d,f.user,null);assert.deepEqual([...f.cache],['unrelated']);f.roles.get('team').permissions.has=bit=>bit===P.Administrator;assert.throws(()=>assertManagedRoles(f.g,f.d,f.roles,f.me));await assert.rejects(synchronizeRoles(f.g,f.d,f.user,{verified:true,division:1,member_rank:'Líder',account_kind:'membro'}));assert.deepEqual([...f.cache],['unrelated']);});

test('diagnostics identify exact variables and every forbidden permission even with bot highest',()=>{
 const f=fixture(2);f.roles.get('team').name='Equipe';f.roles.get('team').permissions.has=bit=>[P.Administrator,P.BanMembers].includes(bit);f.roles.get('moderator').permissions.has=bit=>bit===P.ModerateMembers;
 assert.throws(()=>assertManagedRoles(f.g,f.d,f.roles,f.me),e=>{assert.match(e.message,/DIV_2_ADMIN_ROLE_ID/);assert.match(e.message,/Equipe/);assert.match(e.message,/Administrador, Banir membros/);assert.match(e.message,/DIV_2_MODERATOR_ROLE_ID/);assert.doesNotMatch(e.message,/precisa ficar abaixo/);return true;});
});
test('diagnostics distinguish missing, duplicate, integration, everyone and hierarchy errors',()=>{
 const f=fixture(2);f.d.rankRoles.leader=undefined;f.d.rankRoles.subleader='member';f.roles.delete('high');f.roles.get('moderator').managed=true;f.d.rankRoles.recruiter=f.g.id;f.roles.set(f.g.id,{id:f.g.id});f.me.roles.highest.comparePositionTo=role=>role.id==='rookie'?0:1;
 assert.throws(()=>assertManagedRoles(f.g,f.d,f.roles,f.me),e=>{for(const text of ['DIV_2_LEADER_ROLE_ID: ID não configurado','DIV_2_SUBLEADER_ROLE_ID: repete','DIV_2_HIGH_MEMBER_ROLE_ID: cargo high não encontrado','cargo gerenciado','não use @everyone','DIV_2_ROOKIE_ROLE_ID','precisa ficar abaixo'])assert.ok(e.message.includes(text),text);return true;});
});
